maps:
  test:
    maxPlayers: 4
    traders:
      default:
        1:
          x: 0
          y: 5
          z: 0
        2:
          x: 0
          y: 100
          z: 100
        3:
          x: 100
          y: 100
          z: 0
        4:
          x: 0
          y: 100
          z: 0
        5:
          x: 100
          y: 100
          z: 100
      diamond:
        1:
          x: 5
          y: 5
          z: 5
    generator:
      diamond:
        1:
          x: 75
          y: 100
          z: 75
        2:
          x: 75
          y: 100
          z: 25
        3:
          x: 25
          y: 100
          z: 75
        4:
          x: 25
          y: 100
          z: 25
      emerald:
        1:
          x: 48
          y: 100
          z: 52
        2:
          x: 52
          y: 100
          z: 48
        3:
          x: 52
          y: 100
          z: 52
        4:
          x: 48
          y: 100
          z: 48
    teams:
      RED:
        spawn:
          x: 100
          y: 100
          z: 0
        generator:
          x: 105
          y: 102
          z: 5
        bed:
          x: 100
          y: 102
          z: 5
      BLUE:
        spawn:
          x: 0
          y: 100
          z: 100
        generator:
          x: 5
          y: 102
          z: 105
        bed:
          x: 0
          y: 102
          z: 105
      GREEN:
        spawn:
          x: 0
          y: 100
          z: 0
        generator:
          x: 5
          y: 102
          z: 5
        bed:
          x: 0
          y: 102
          z: 5
      YELLOW:
        spawn:
          x: 100
          y: 100
          z: 100
        generator:
          x: 105
          y: 102
          z: 105
        bed:
          x: 100
          y: 102
          z: 105
trader:
  default:
    tabs:
      armor:
        0:
          slotType: tabChange
          item: DIAMOND_SWORD
          name: Weapon
        1:
          slotType: buyable
          item: DIAMOND_CHESTPLATE
          name: Chestplate
          resourse: IRON
          price: 4
        2:
          slotType: default
          item: GLASS
          name: " "
      weapon:
        0:
          slotType: default
          item: GLASS
          name: " "
        1:
          slotType: tabChange
          item: DIAMOND_CHESTPLATE
          name: Armor
        2:
          slotType: buyable
          item: DIAMOND_SWORD
          name: Sword
          resourse: GOLD
          price: 2
      tools:

  diamond:
    tabs:
      upgrades: